// Generated from the Phase 1 OpenAPI contract. Run shared/generate_types.py after contract changes.
export type User = { id:string; tenant_id:string; email:string; name:string; role:string; ward_id:string|null }
export type Patient = { id:string; ward_id:string; mrn:string; national_id_last4:string; name:string; date_of_birth:string; sex:string; bed:string; admission_reason:string; admitted_at:string; allergies_json:Array<{substance:string;reaction:string;severity:string}>; code_status:string; isolation_status:string; flags_json:string[]; photo_status:string; accountable_nurse_name?:string; latest_score:number|null; observation_time:string|null; open_tasks:number; overdue_tasks:number; observations?:Observation[]; tasks?:Task[]; medications?:Medication[]; assessments?:Assessment[]; care_plans?:CarePlan[] }
export type Observation = { id:string; recorded_at:string; respiratory_rate:number; oxygen_saturation:number; systolic_bp:number; pulse:number; temperature:number; consciousness:string; score:number; escalation_level:string; source:string }
export type Task = { id:string; patient_id:string; patient_name?:string; bed?:string; title:string; description:string; priority:string; status:string; due_at:string; assigned_to:string|null; version:number }
export type Medication = { id:string; patient_id:string; medication_name:string; dose_value:number; dose_unit:string; route:string; schedule:string; due_at:string; high_alert:number; status:string; source:string }
export type Assessment = { id:string; assessment_type:string; risk_level:string; score:number|null; findings:string; actions_json:string[]; assessed_at:string }
export type CarePlan = { id:string; problem:string; goal:string; interventions_json:string[]; status:string; owner_id:string; evaluation:string|null; updated_at:string; version:number }
export type Nurse = { id:string; name:string; role:string }
export type HandoverRecord = { id:string; patient_id:string; patient_name:string; bed:string; sender_id:string; receiver_id:string; sender_name:string; receiver_name:string; status:string; situation:string; recommendation:string; unresolved_tasks_json:Array<{id:string;title:string;priority:string;due_at:string;status:string}> }
export type WardBoard = { ward:{id:string;name:string;code:string;specialty:string}; patients:Patient[]; generated_at:string; source:string }
